# Generated by ‘nixos-generate-config’, then trimmed: the fileSystems and
# swapDevices blocks were removed because disko (hosts/pavg15/disk.nix) owns the
# disk layout. Keep only the detected hardware bits here. If you regenerate this
# file, re-strip the fileSystems/swapDevices stanzas to avoid clashing with disko.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # fileSystems + swapDevices are declared by disko (hosts/pavg15/disk.nix), not here.

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
